### PR TITLE
Zsh completions

### PR DESCRIPTION
**Pull request by alkersan**
Hi Yuriy,
would you accept this set of functions for easier terminal exeprience?
Completions done very similar to [docker-compose](https://github.com/docker/compose/tree/master/contrib/completion) and [docker](https://github.com/docker/docker/tree/master/contrib/completion)

### CODE REVIEW

**Comment by alkersan** [comment]
I've seen the changes in recent release and added completions for `pin` and some additional flags

**Comment by ybogdanov** [comment]
Hi @alkersan, cool thanks!
Any need for documentation on how to use it?

**Comment by alkersan** [comment]
I've added small mention about availability of completions. Usually, if somebody looks for them he already knows what to do next, but reference to instructions is also present.
And regarding Bash shell - I haven't used it for a long already, but I could spend some time and add completions for it later.

**Comment by ybogdanov** [comment]
Thanks, @alkersan!

**Pull request merged**
